### ISSUE TITLE
Nothing is displayed 

### ISSUE THREAD

**Issue by mrtpcet** [mayflower/PayForMe#28] opened 2020-05-30 23:50 UTC
iOS 13.5

I have entered the address of my cospend project on my nextcloud server but nothing is displayed in the application.

**Comment by Hustenbonbon** [comment] 2020-06-08 09:15
You mean you have entered the address of the project inside the app, right?
The way it is meant to be done:
In the field server adress: "mynextcloud.com"
In the project id field the name of the project
in the password field the project password.

Putting in the whole string combined in the server address field won't work

**Comment by mrtpcet** [comment] 2020-06-08 09:26
Yeah, I get that, but nothing's showing. 
It's weird because the content of my project was displayed once but after that it looks empty in the application!

Thanks

**Comment by horsedriver** [comment] 2020-07-23 05:33
any news on this?

**Comment by Hustenbonbon** [comment] 2020-08-17 12:56
Will refactor the whole authentification part and add a QR-code authentification, I hope this will solve this issue, otherwise I'll need to have a look again.
I couldn't reproduce this bug.

**Comment by Hustenbonbon** [comment] 2020-12-07 13:07
Every possible bug I could imagine producing this should be fixed with the new release, please reopen and tell me if not.

**Closed** 2020-12-07 13:07 UTC
