### ISSUE TITLE
Server can't be found

### ISSUE THREAD

**Issue by psychosis448** [mayflower/PayForMe#48] opened 2022-01-24 18:30 UTC
Hi,

yesterday I added Cospend to my Nextcloud instance.  
Unfortunately `PayForMe` does not seem to find my server.  
It just says `Could not find server` (password was correctly entered in the screenshot beyond).  
The server is accessible on my local network by its static ip.    
I can access the project via password protected guest access as well.  
Is the ip maybe the problem?

NextCloudPi version: v1.46.7
NextCloudPi image: NextCloudPi_10-07-21
Cospend version: v1.3.7
PayForMe version: v2.3.4

<img src="https://user-images.githubusercontent.com/29786108/150842156-07d89c3a-53e9-4537-b055-9d3837c6413d.png" width="260">

**Comment by Hustenbonbon** [comment] 2022-01-24 20:43
Hey, 
thanks for the info! Two questions before I start digging in:
1. Are you sure you have HTTPS on your nextcloud?
2. Did you try with a password protected link?

**Comment by psychosis448** [comment] 2022-01-25 17:52
Hey,

1. yes, but it's only using a self-signed certificate
2. yes, i tested all possible links & qr codes, none of them worked

**Comment by Hustenbonbon** [comment] 2022-07-13 08:26
Hey, I couldn't reproduce it back then (Didn't have the time to recreate a setup like this).
Since then I overhauled the whole project onboarding logic, can you check if it is still broken?

**Comment by Hustenbonbon** [comment] 2022-07-29 08:40
Closing for now, please re-open if the problem persists

**Closed by Hustenbonbon** 2022-07-29 08:40 UTC

**Comment by ATS-ONE** [comment] 2022-12-21 23:33
Hello Hustenbonbon,

I'm sorry to disturb you, but I have the same issue. Have tried multiple ways but the PayForMe app always tells me "Could not find server". Trying it for weeks now. During the connection, will the SSL certificate be checked?

May you please help me? Thanks!
